# Generated by Django 6.0 on 2025-12-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=100)),
                ('aircraft_id', models.CharField(max_length=100)),
                ('flight_date', models.DateTimeField()),
                ('passengers', models.IntegerField()),
                ('form', models.CharField(max_length=100)),
                ('to', models.CharField(max_length=100)),
                ('status', models.CharField()),
            ],
        ),
    ]
