# Generated by Django 6.0 on 2026-01-05 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending'),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='currency',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='payment_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='payment_status',
            field=models.CharField(choices=[('held', 'held'), ('refund', 'refund'), ('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid'),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
