# Generated by Django 6.0 on 2026-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked', '0002_remove_bookedmodel_status_bookedmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookedmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
