# Generated by Django 6.0 on 2026-01-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked', '0003_bookedmodel_created_at_bookedmodel_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='payment_status',
            field=models.CharField(choices=[('held', 'held'), ('refund', 'refund'), ('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
