# Generated by Django 6.0 on 2026-01-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booked', '0004_alter_bookedmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmodel',
            name='booking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookedmodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
